
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Chapter_WaveGroup : Luban.BeanBase
{
    public Chapter_WaveGroup(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);WaveIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); WaveIds[__index0] = __e0;}}
    }

    public static Chapter_WaveGroup DeserializeChapter_WaveGroup(ByteBuf _buf)
    {
        return new Chapter_WaveGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 波次组id
    /// </summary>
    public readonly int[] WaveIds;
   
    public const int __ID__ = -2137325228;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "WaveIds:" + Luban.StringUtil.CollectionToString(WaveIds) + ","
        + "}";
    }
}

}

