
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Chapter : Luban.BeanBase
{
    public Chapter(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (eChapterType)_buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);WaveGroups = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); WaveGroups[__index0] = __e0;}}
    }

    public static Chapter DeserializeChapter(ByteBuf _buf)
    {
        return new Chapter(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 关卡玩法类型
    /// </summary>
    public readonly eChapterType Type;
    /// <summary>
    /// 章节组
    /// </summary>
    public readonly int[] WaveGroups;
   
    public const int __ID__ = -1891298259;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "waveGroups:" + Luban.StringUtil.CollectionToString(WaveGroups) + ","
        + "}";
    }
}

}

