
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Chapter_Mission : Luban.BeanBase
{
    public Chapter_Mission(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Wave = _buf.ReadInt();
        Time = _buf.ReadFloat();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MonsterId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); MonsterId[__index0] = __e0;}}
    }

    public static Chapter_Mission DeserializeChapter_Mission(ByteBuf _buf)
    {
        return new Chapter_Mission(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 波次
    /// </summary>
    public readonly int Wave;
    /// <summary>
    /// 当前mission时间(秒)
    /// </summary>
    public readonly float Time;
    /// <summary>
    /// 怪物id
    /// </summary>
    public readonly int[] MonsterId;
   
    public const int __ID__ = 310335322;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "wave:" + Wave + ","
        + "time:" + Time + ","
        + "MonsterId:" + Luban.StringUtil.CollectionToString(MonsterId) + ","
        + "}";
    }
}

}

