
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Charactor : Luban.BeanBase
{
    public Charactor(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (eEntityType)_buf.ReadInt();
        ResourceID = _buf.ReadInt();
        SurvivalTime = _buf.ReadFloat();
    }

    public static Charactor DeserializeCharactor(ByteBuf _buf)
    {
        return new Charactor(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 实体类型
    /// </summary>
    public readonly eEntityType Type;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly int ResourceID;
    /// <summary>
    /// 生存时长
    /// </summary>
    public readonly float SurvivalTime;
   
    public const int __ID__ = -726803393;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "ResourceID:" + ResourceID + ","
        + "survivalTime:" + SurvivalTime + ","
        + "}";
    }
}

}

