
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum eAttribute
    {
        /// <summary>
        /// 攻击
        /// </summary>
        enum_Attack = 1,
        /// <summary>
        /// 血量
        /// </summary>
        enum_Hp = 2,
    }

} 

