
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum eEntityType
    {
        Player = 1,
        Monster = 2,
        Elite = 3,
        Boss = 4,
        NPC = 5,
        Object = 6,
    }

} 

