
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Resource : Luban.BeanBase
{
    public Resource(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Path = _buf.ReadString();
    }

    public static Resource DeserializeResource(ByteBuf _buf)
    {
        return new Resource(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = -276420562;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Path:" + Path + ","
        + "}";
    }
}

}

