
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbChapter_WaveGroup
{
    private readonly System.Collections.Generic.Dictionary<int, Chapter_WaveGroup> _dataMap;
    private readonly System.Collections.Generic.List<Chapter_WaveGroup> _dataList;
    
    public TbChapter_WaveGroup(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chapter_WaveGroup>();
        _dataList = new System.Collections.Generic.List<Chapter_WaveGroup>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chapter_WaveGroup _v;
            _v = global::cfg.Chapter_WaveGroup.DeserializeChapter_WaveGroup(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chapter_WaveGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<Chapter_WaveGroup> DataList => _dataList;

    public Chapter_WaveGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chapter_WaveGroup Get(int key) => _dataMap[key];
    public Chapter_WaveGroup this[int key] => _dataMap[key];
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

