
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbCharactor
{
    private readonly System.Collections.Generic.Dictionary<int, Charactor> _dataMap;
    private readonly System.Collections.Generic.List<Charactor> _dataList;
    
    public TbCharactor(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Charactor>();
        _dataList = new System.Collections.Generic.List<Charactor>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Charactor _v;
            _v = global::cfg.Charactor.DeserializeCharactor(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Charactor> DataMap => _dataMap;
    public System.Collections.Generic.List<Charactor> DataList => _dataList;

    public Charactor GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Charactor Get(int key) => _dataMap[key];
    public Charactor this[int key] => _dataMap[key];
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

