
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbChapter_Mission
{
    private readonly System.Collections.Generic.Dictionary<int, Chapter_Mission> _dataMap;
    private readonly System.Collections.Generic.List<Chapter_Mission> _dataList;
    
    public TbChapter_Mission(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chapter_Mission>();
        _dataList = new System.Collections.Generic.List<Chapter_Mission>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chapter_Mission _v;
            _v = global::cfg.Chapter_Mission.DeserializeChapter_Mission(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chapter_Mission> DataMap => _dataMap;
    public System.Collections.Generic.List<Chapter_Mission> DataList => _dataList;

    public Chapter_Mission GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chapter_Mission Get(int key) => _dataMap[key];
    public Chapter_Mission this[int key] => _dataMap[key];
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

