
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbResource
{
    private readonly System.Collections.Generic.Dictionary<int, Resource> _dataMap;
    private readonly System.Collections.Generic.List<Resource> _dataList;
    
    public TbResource(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Resource>();
        _dataList = new System.Collections.Generic.List<Resource>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Resource _v;
            _v = global::cfg.Resource.DeserializeResource(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Resource> DataMap => _dataMap;
    public System.Collections.Generic.List<Resource> DataList => _dataList;

    public Resource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Resource Get(int key) => _dataMap[key];
    public Resource this[int key] => _dataMap[key];
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

